name: Android Test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Lint check
        run: bash ./gradlew ktlintCheck
      - name: Build
        run: bash ./gradlew build
      - name: Unit test
        run: bash ./gradlew test --stacktrace